default:
  tags:
    - docker


stages:
  - build
  - deploy

build_job:
  stage: build
  image: tpepchi9/web_base:latest
  script:
    - echo "test"
    - python3 -V  # Print out python version for debugging
    - python3 manage.py test

deploy_job:
  stage: deploy
  image: tpepchi9/web_base:latest
  before_script: #在container裡面建立SSH 
    # 预先装 ssh-agent
    - 'which ssh-agent || ( apk update && apk add openssh-client)'
    # 启动服务
    - eval $(ssh-agent -s)
    # 将私钥写入deploy.key 文件
    - echo "$SSH_PRIVATE_KEY" > deploy.key
    # 配置较低权限
    - chmod 0600 deploy.key
    # 注入密钥
    - ssh-add deploy.key
    - mkdir -p ~/.ssh    
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "test"
    - ssh-copy-id root@10.80.1.24
    - ssh root@10.80.1.24 "cd /tttest && rm ./* -rf && git clone http://10.80.1.20/root/ssh_docker_test.git"
    - scp docker-compose.yml root@10.80.1.24:/tttest
    # - ssh root@10.80.1.24 "cd /tttest/ssh_docker_test/PJ83_db_api && chmod -x run.sh"
    - ssh root@10.80.1.24 "cd /tttest && docker-compose -f docker-compose.yml down && docker-compose -f docker-compose.yml up -d"
    - hostname
    - echo "OK"
  # environment:
  #   name: UAT
  #   url: http://10.80.1.24
  when: manual
